### ISSUE TITLE
Layer Selection Index

### ISSUE THREAD

**Issue by cedricduriau** [cedricduriau/Cryptomatte#19]
Layer selection indexes are stored as both `string` and `number` in the `cryptomatte_utlities` module when reading the metadata. Convert all to `string` to avoid table/array index lookup issues.

**Comment by AndrewHazelden** [comment]
What would your opinion be of adding a Cryptomatte modifier fuse that would let someone keyframe animate through an integer based list of Crypto based keyable surfaces?

This could be used as a diagnostic tool for debugging matte issues, and for helping with behind the scenes making-of info graphic illustrations.

**Comment by cedricduriau** [comment]
> What would your opinion be of adding a Cryptomatte modifier fuse that would let someone keyframe animate through an integer based list of Crypto based keyable surfaces?

So building matte names on keyframes and driving the matte selection string, correct? If so, we could do something as such. You might want to talk to Kristof about this, he has a hell of a lot of procedural (text) nodes that could help out with this.

> This could be used as a diagnostic tool for debugging matte issues, and for helping with behind the scenes making-of info graphic illustrations.

Yeah indeed, sounds neat!
