### ISSUE TITLE
GUI Controls on new lines

### ISSUE THREAD

**Issue by cedricduriau** [cedricduriau/Cryptomatte#29]
Fusion >=16.x crops the label of controls if they do not fit the width.
Put all controls on new lines (as standard in >=16.x) for consistency and readability.

**Comment by AndrewHazelden** [comment]
Hi. I did a quick usability test of the Crypto v1.4 Beta 3 fuse on Fusion Studio v17.1. The Inspector view's "new UI skin" causes the controls to get clipped at the default window width setting for the Inspector view. One can expand the Inspector view wider manually if they want to be able to read the "Matte Only" control label fully.
![Crypto Node nspector View - Matte Only Clipped off](https://user-images.githubusercontent.com/909728/113769516-6fb2a800-96f7-11eb-9869-a5c609bda4e9.png)
![Revised Fusion Screenshot](https://user-images.githubusercontent.com/909728/113769519-704b3e80-96f7-11eb-802a-49164c9365df.png)

**Comment by cedricduriau** [comment]
Hi Andrew

Yup, you're right. Although this entire section has been changed as well since #33.
Pull master for latest goodies. Next beta will contain these changes. Stay tuned.

Cheers
Cedric
