### ISSUE TITLE
Block multipart EXR until fully supported

### ISSUE THREAD

**Issue by cedricduriau** [cedricduriau/Cryptomatte#49]
Multipart EXR images are not supported and might cause undesired behavior. Either a partial/full first part support (hard coded until now) or errors/crashes will occur. Raise an error to block multipart EXR use.

**Comment by AndrewHazelden** [comment]
You might want to talk to Peter L. about Multipart EXRIO usage so you don't need to actively block media in this format going forward.

**Comment by cedricduriau** [comment]
Good suggestion Andrew, but we most likely already have all the tools ready to support this, we just need to make work of it. I have an agreement with Jonah that we won't support multipart EXR for the next release. But to avoid any confusion/unwanted errors, I put this in place for now.

**Comment by AndrewHazelden** [comment]
Okay...
