### ISSUE TITLE
Lua Script Header Expansion

### ISSUE THREAD

**Issue by AndrewHazelden** [cedricduriau/Cryptomatte#58]
Hi Cédric.

I'd like to propose an expansion of the amount of information present in the Cryptomatte for Fusion headers:

```--[[
Title      : Cryptomatte for Fusion
Version    : 1.4 Beta 4
Release    : 2021-04-23
Requires   : Fusion 9.0.2 - 17.1.1+
Requires   : Resolve 15.1 - 17.1.1+
Optional   : cjson
Created by : Cédric Duriau         [duriau.cedric@live.be]
             Kristof Indeherberge  [xmnr0x23@gmail.com]
             Andrew Hazelden       [andrew@andrewhazelden.com]
--]]
```

The files effected are:

- Config/cryptomatte_shortcuts.fu
- Fuses/Matte/cryptomatte.fuse
- Modules/Lua/cryptomatte_utilities.lua
- Modules/Lua/test_cryptomatte_utilities.lua

**Comment by cedricduriau** [comment]
Hi @AndrewHazelden 

Makes total sense, will do and silently move the tag to the merged commit.

Cheers
Cedric

**Comment by cedricduriau** [comment]
Title seems redundant due to the nature of the software requirement imho. I made the version number the same as the tag, this way it's a single find and replace for all version occurrences. Except the fuse version number as int.

**Comment by cedricduriau** [comment]
I also already set the tag to 1.4.0 for release prep, this way no more work needs to be done by myself for release. @jonahf will take it over from there.

**Comment by cedricduriau** [comment]
Merged and retagged, thanks Andrew!

**Comment by AndrewHazelden** [comment]
Re: "Title seems redundant comment." 

Have you ever looked a manual deployments of lua modules and other scripts IRL in the Fusion ecosystem?

**Comment by AndrewHazelden** [comment]
No one maintains the structure of the Psyop repo on disk when they ingest the files... ;)

**Comment by cedricduriau** [comment]
Could you clarify both of your comments and their point?

**Comment by AndrewHazelden** [comment]
For example JPDoc from WSL couldn't even detect he had multiple Cryptomatte versions in his Fusion PathMap folders.

Deployment of several files to the correct PathMap folder locations, and with matching version numbers for files is hit and miss IRL if you expect actual compositors to do the manual copy/paste deployment, not TDs. 🤓

**Comment by AndrewHazelden** [comment]
Here is an example of all this deployment related stuff playing out:

https://www.steakunderwater.com/wesuckless/viewtopic.php?p=32510#p32510

**Comment by AndrewHazelden** [comment]
Also for the software requirement being redundant, from my perspective I can likely find 25+ individual posts between the BMD Forums, WSL, Resolve Reddit, FB Groups, and Gamma/Lift/Gain forum where users think (or expect/hope that) Cryptomatte for Resolve works on the Edit or Color page, not to mention people trying to use MediaIn node.

You're only offering "Cryptomatte for Fusion page/Fusion Standalone" if I had to classify where the tool works.

Technically an Effects Template macro could make Cryptomatte work on the Edit page if the fuse added workarounds for the metadata filename thing but that's "another pair of sleeves".

**Comment by cedricduriau** [comment]
> For example JPDoc from WSL couldn't even detect he had multiple Cryptomatte versions in his Fusion PathMap folders.

Understandable considering the nodes aren't actually versioned. Kristof had the same issue recently.

> Deployment of several files to the correct PathMap folder locations, and with matching version numbers for files is hit and miss IRL if you expect actual compositors to do the manual copy/paste deployment, not TDs. 🤓

I still don't understand where you're going here.

> Also for the software requirement being redundant,

I never said the software requirement was redundant? I was talking about the title. The software requirements have been added.

>  from my perspective I can likely find 25+ individual posts between the BMD Forums, WSL, Resolve Reddit, FB Groups, and Gamma/Lift/Gan forum where users think Cryptomatte for Resolve works on the Edit or Color page, not to mention people trying to use MediaIn node.

This sounds like a lack of documentation to me, we certainly can cover this to reduce further confusion.

> You're only offering "Cryptomatte for Fusion page/Fusion Standalone" if I had to classify where the tool works.

See previous answer.

> Technically an Effects Template macro could make Cryptomatte work on the Edit page if the fuse added workarounds for the metadata filename thing but that's "another pair of sleeves".

Besides indeed going off topic, we already spoke about this. Nothing stops anyone to write a toolkit/node set for Resolve to allow this.

I'm also just a human being Andrew, don't forget that.

Cheers
Cédric

**Comment by AndrewHazelden** [comment]
> Could you clarify both of your comments and their point?

Sure. A script or any tool should clearly label its intended use case, supported environment, and ideally it's installation location.

Any plugin or tool I get from a commercial vendor mark's that information clearly. "V-Ray for Maya", "MtoA" aka "Maya to Arnold", or "RenderMan 24 for Blender" are in the script files.

If I were to have a file called "Cryptomatte.py" in a downloads folder for example, a few months later would be ambiguous for it's use case and installation location if I was not someone who used a git client to sync a full repo. 

What path does this file go in, etc..

I've yet to meet a core compositor who doesn't cherry pick and download files one at a time from GitHub since they don't use git from the cli.

**Comment by AndrewHazelden** [comment]
I'll stop commenting though as it's beyond the scope of this thread and more about self documenting code, etc. :)

**Comment by AndrewHazelden** [comment]
Have a great weekend. Thanks for the updates.
