### ISSUE TITLE
Cryptomatte v1.2.2 FUSE_VERSION Tag Version Mismatch

### ISSUE THREAD

**Issue by AndrewHazelden** [cedricduriau/Cryptomatte#7]
Hi @cedricduriau.

Thanks for adding the extra Fuse details like:

```
FUSE_CATEGORY = "Matte"
FUSE_COMPANY = "Psyop"
FUSE_HELP = "https://www.steakunderwater.com/wesuckless/viewtopic.php?f=6&t=1027"
FUSE_URL = "https://github.com/Psyop/Cryptomatte"
FUSE_VERSION = 121
```

I am working with Greg Bovine to update the Reactor atom packaged version of Cryptomatte to include the Cryptomatte v1.2.2 release features.

From looking over the code you updated to make the new release, I wanted to comment that the "Official" Cryptomatte v1.2.2 Fusion files had a Cryptomatte.fuse versioning error in the:
`FUSE_VERSION = 121` tag where it didn't get updated to `122`.

**Comment by cedricduriau** [comment]
Hi @AndrewHazelden

Just checked again and Jonah fixed that for me 17 days ago.
Which branch are you on?

Cheers
Cedric

**Comment by cedricduriau** [comment]
Hi @AndrewHazelden

Found it. Thanks!

Cheers
Cedric
